import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    with page.expect_popup() as page1_info:
        page.goto("https://shipdlx.3gtms.com/web/login")
    page1 = page1_info.value
    page1.close()
    page.get_by_role("textbox", name="* Username:").click()
    page.get_by_role("textbox", name="* Username:").fill("Demo.DLX")
    page.get_by_role("textbox", name="* Username:").press("Tab")
    page.get_by_role("textbox", name="* Password:").fill("DLX1")
    page.get_by_role("textbox", name="* Password:").press("Enter")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="Add Order").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#orderNum").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#orderNum").fill("Order1234567")
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_sourceId").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_sourceId").fill("demo")
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_sourceId").press("Enter")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("link", name="Demo Location, LOC-00010881,").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_destinationId").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_destinationId").fill("lowes")
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#robustSearchText_destinationId").press("Enter")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("link", name="Lowes, LOC-00010885, Sioux City,").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator(".jqx-icon").first.click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("gridcell", name="13").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator(".jqx-icon.jqx-icon-calendar.jqx-icon-calendar-hover").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("gridcell", name="13").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator(".jqx-icon.jqx-icon-calendar.jqx-icon-calendar-hover").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("gridcell", name="15").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator(".jqx-icon.jqx-icon-calendar.jqx-icon-calendar-hover").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("gridcell", name="15").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("button", name="Add Order Line").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Description:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Description:").fill("Generators")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Gross Wt:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Gross Wt:").fill("20000")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Net Wt:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Net Wt:").fill("20000")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="HU Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="HU Count:").fill("1")
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#handlingUnitTypeIdEditor_handlingUnitTypeIdEditor").select_option("3")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").fill("1")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("div").filter(has_text="Please ChooseBXCACSDrumEAPailRollTotes").nth(5).click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Piece Count:").fill("")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("button", name="Save & Close").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("button", name=" Add Another Reference Number").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator("#rnSelect0").select_option("567")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Value").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("textbox", name="Value").fill("Customer1234567")
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("button", name="Get Rates").click()
    page.locator("iframe[name=\"Form\"]").content_frame.locator(".jqx-checkbox-default.jqx-checkbox-default-Blue_A6C5D9.jqx-fill-state-normal.jqx-fill-state-normal-Blue_A6C5D9.jqx-rc-all.jqx-rc-all-Blue_A6C5D9.jqx-checkbox-hover > div").click()
    page.locator("iframe[name=\"Form\"]").content_frame.get_by_role("button", name="Select & Save Order").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
